version: '3.8'

services:
  db:
    hostname: db
    image: ankane/pgvector  # Includes pgvector
    ports:
      - "5555:5432"  # Only for development
    restart: always
    environment:
      POSTGRES_DB: llm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "llm"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/llm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8888:8888"
    depends_on:
      - db
    # Add retries for database connection in your Spring Boot configuration

volumes:
  postgres-data:
